WIP (didn't get working yet)
got to a bunch of compile errors, looking like:

```
cargo build
   Compiling capture v0.1.0 (/Users/mxm/Library/Mobile Documents/com~apple~CloudDocs/Code/mine/refraction/refraction/capture)
error[E0432]: unresolved import `tokio::net::TcpStream`
 --> capture/src/async_imap.rs:4:5
  |
4 | use tokio::net::TcpStream;
  |     ^^^^^^^^^^^^^^^^^^^^^ no `TcpStream` in `net`
  |
help: consider importing this struct instead
  |
4 | use std::net::TcpStream;
  |     ~~~~~~~~~~~~~~~~~~~

warning: unused import: `bail`
 --> capture/src/async_imap.rs:2:14
  |
2 | use anyhow::{bail, Result};
  |              ^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `futures::TryStreamExt`
 --> capture/src/async_imap.rs:3:5
  |
3 | use futures::TryStreamExt;
  |     ^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0432`.
warning: `capture` (lib) generated 2 warnings
error: could not compile `capture` (lib) due to previous error; 2 warnings emitted
➜  capture git:(refraction-capture-async-imap) ✗ cargo build
   Compiling socket2 v0.5.4
   Compiling mio v0.8.8
   Compiling tokio v1.32.0
   Compiling async-native-tls v0.5.0
   Compiling async-imap v0.9.1
error[E0252]: the name `AsyncRead` is defined multiple times
 --> /Users/mxm/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-native-tls-0.5.0/src/runtime.rs:9:28
  |
2 | pub(crate) use futures_util::io::{AsyncRead, AsyncWrite};
  |                                   --------- previous import of the trait `AsyncRead` here
...
9 | pub(crate) use tokio::io::{AsyncRead, AsyncReadExt, AsyncWrite};
  |                            ^^^^^^^^^ `AsyncRead` reimported here
  |
  = note: `AsyncRead` must be defined only once in the type namespace of this module
help: you can use `as` to change the binding name of the import
  |
9 | pub(crate) use tokio::io::{AsyncRead as OtherAsyncRead, AsyncReadExt, AsyncWrite};
  |                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~

error[E0252]: the name `AsyncReadExt` is defined multiple times
 --> /Users/mxm/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-native-tls-0.5.0/src/runtime.rs:9:39
  |
6 | pub(crate) use futures_util::io::{AsyncReadExt, AsyncWriteExt};
  |                                   ------------ previous import of the trait `AsyncReadExt` here
...
9 | pub(crate) use tokio::io::{AsyncRead, AsyncReadExt, AsyncWrite};
  |                                       ^^^^^^^^^^^^ `AsyncReadExt` reimported here
  |
  = note: `AsyncReadExt` must be defined only once in the type namespace of this module
help: you can use `as` to change the binding name of the import
  |
9 | pub(crate) use tokio::io::{AsyncRead, AsyncReadExt as OtherAsyncReadExt, AsyncWrite};
  |                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

error[E0252]: the name `AsyncWrite` is defined multiple times
 --> /Users/mxm/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-native-tls-0.5.0/src/runtime.rs:9:53
  |
2 | pub(crate) use futures_util::io::{AsyncRead, AsyncWrite};
  |                                              ---------- previous import of the trait `AsyncWrite` here
...
9 | pub(crate) use tokio::io::{AsyncRead, AsyncReadExt, AsyncWrite};
  |                                                     ^^^^^^^^^^ `AsyncWrite` reimported here
  |
  = note: `AsyncWrite` must be defined only once in the type namespace of this module
help: you can use `as` to change the binding name of the import
  |
9 | pub(crate) use tokio::io::{AsyncRead, AsyncReadExt, AsyncWrite as OtherAsyncWrite};
  |                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

error: only one of 'runtime-async-std' or 'runtime-tokio' features must be enabled
  --> /Users/mxm/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-native-tls-0.5.0/src/lib.rs:38:1
   |
38 | compile_error!("only one of 'runtime-async-std' or 'runtime-tokio' features must be enabled");
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0407]: method `poll_shutdown` is not a member of trait `AsyncWrite`
   --> /Users/mxm/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-native-tls-0.5.0/src/tls_stream.rs:138:5
    |
138 | /     fn poll_shutdown(mut self: Pin<&mut Self>, ctx: &mut Context<'_>) -> Poll<io::Result<()>> {
139 | |         match self.with_context(ctx, |s| s.shutdown()) {
140 | |             Ok(()) => Poll::Ready(Ok(())),
141 | |             Err(ref e) if e.kind() == io::ErrorKind::WouldBlock => Poll::Pending,
142 | |             Err(e) => Poll::Ready(Err(e)),
143 | |         }
144 | |     }
    | |_____^ not a member of trait `AsyncWrite`

error[E0252]: the name `Read` is defined multiple times
  --> /Users/mxm/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-imap-0.9.1/src/client.rs:16:17
   |
9  | use async_std::io::{Read, Write, WriteExt};
   |                     ---- previous import of the trait `Read` here
...
16 | use tokio::io::{AsyncRead as Read, AsyncWrite as Write, AsyncWriteExt};
   |                 ^^^^^^^^^^^^^^^^^ `Read` reimported here
   |
   = note: `Read` must be defined only once in the type namespace of this module
help: you can use `as` to change the binding name of the import
   |
16 | use tokio::io::{AsyncRead as OtherRead, AsyncWrite as Write, AsyncWriteExt};
   |                 ~~~~~~~~~~~~~~~~~~~~~~

error[E0252]: the name `Write` is defined multiple times
  --> /Users/mxm/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-imap-0.9.1/src/client.rs:16:36
   |
9  | use async_std::io::{Read, Write, WriteExt};
   |                           ----- previous import of the trait `Write` here
...
16 | use tokio::io::{AsyncRead as Read, AsyncWrite as Write, AsyncWriteExt};
   |                                    ^^^^^^^^^^^^^^^^^^^ `Write` reimported here
   |
   = note: `Write` must be defined only once in the type namespace of this module
help: you can use `as` to change the binding name of the import
   |
16 | use tokio::io::{AsyncRead as Read, AsyncWrite as OtherWrite, AsyncWriteExt};
   |                                    ~~~~~~~~~~~~~~~~~~~~~~~~

error[E0252]: the name `Read` is defined multiple times
  --> /Users/mxm/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-imap-0.9.1/src/extensions/idle.rs:18:10
   |
10 |     io::{Read, Write},
   |          ---- previous import of the trait `Read` here
...
18 |     io::{AsyncRead as Read, AsyncWrite as Write},
   |          ^^^^^^^^^^^^^^^^^ `Read` reimported here
   |
   = note: `Read` must be defined only once in the type namespace of this module
help: you can use `as` to change the binding name of the import
   |
18 |     io::{AsyncRead as OtherRead, AsyncWrite as Write},
   |          ~~~~~~~~~~~~~~~~~~~~~~

error[E0252]: the name `Write` is defined multiple times
  --> /Users/mxm/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-imap-0.9.1/src/extensions/idle.rs:18:29
   |
10 |     io::{Read, Write},
   |                ----- previous import of the trait `Write` here
...
18 |     io::{AsyncRead as Read, AsyncWrite as Write},
   |                             ^^^^^^^^^^^^^^^^^^^ `Write` reimported here
   |
   = note: `Write` must be defined only once in the type namespace of this module
help: you can use `as` to change the binding name of the import
   |
18 |     io::{AsyncRead as Read, AsyncWrite as OtherWrite},
   |                             ~~~~~~~~~~~~~~~~~~~~~~~~

error[E0252]: the name `timeout` is defined multiple times
  --> /Users/mxm/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-imap-0.9.1/src/extensions/idle.rs:19:5
   |
9  |     future::timeout,
   |     --------------- previous import of the value `timeout` here
...
19 |     time::timeout,
   |     ^^^^^^^^^^^^^ `timeout` reimported here
   |
   = note: `timeout` must be defined only once in the value namespace of this module
help: you can use `as` to change the binding name of the import
   |
19 |     time::timeout as other_timeout,
   |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

error[E0252]: the name `Read` is defined multiple times
  --> /Users/mxm/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-imap-0.9.1/src/imap_stream.rs:12:17
   |
5  | use async_std::io::{Read, Write, WriteExt};
   |                     ---- previous import of the trait `Read` here
...
12 | use tokio::io::{AsyncRead as Read, AsyncWrite as Write, AsyncWriteExt};
   |                 ^^^^^^^^^^^^^^^^^ `Read` reimported here
   |
   = note: `Read` must be defined only once in the type namespace of this module
help: you can use `as` to change the binding name of the import
   |
12 | use tokio::io::{AsyncRead as OtherRead, AsyncWrite as Write, AsyncWriteExt};
   |                 ~~~~~~~~~~~~~~~~~~~~~~

error[E0252]: the name `Write` is defined multiple times
  --> /Users/mxm/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-imap-0.9.1/src/imap_stream.rs:12:36
   |
5  | use async_std::io::{Read, Write, WriteExt};
   |                           ----- previous import of the trait `Write` here
...
12 | use tokio::io::{AsyncRead as Read, AsyncWrite as Write, AsyncWriteExt};
   |                                    ^^^^^^^^^^^^^^^^^^^ `Write` reimported here
   |
   = note: `Write` must be defined only once in the type namespace of this module
help: you can use `as` to change the binding name of the import
   |
12 | use tokio::io::{AsyncRead as Read, AsyncWrite as OtherWrite, AsyncWriteExt};
   |                                    ~~~~~~~~~~~~~~~~~~~~~~~~

error: only one of 'runtime-async-std' or 'runtime-tokio' features must be enabled
  --> /Users/mxm/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-imap-0.9.1/src/lib.rs:83:1
   |
83 | compile_error!("only one of 'runtime-async-std' or 'runtime-tokio' features must be enabled");
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0119]: conflicting implementations of trait `std::io::Read` for type `StdAdapter<_>`
  --> /Users/mxm/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-native-tls-0.5.0/src/std_adapter.rs:48:1
   |
35 | impl<S> Read for StdAdapter<S>
   | ------------------------------ first implementation here
...
48 | impl<S> Read for StdAdapter<S>
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `StdAdapter<_>`

error[E0119]: conflicting implementations of trait `futures_util::AsyncRead` for type `tls_stream::TlsStream<_>`
  --> /Users/mxm/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-native-tls-0.5.0/src/tls_stream.rs:92:1
   |
78 | impl<S> AsyncRead for TlsStream<S>
   | ---------------------------------- first implementation here
...
92 | impl<S> AsyncRead for TlsStream<S>
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `tls_stream::TlsStream<_>`

Some errors have detailed explanations: E0119, E0252, E0407.
For more information about an error, try `rustc --explain E0119`.
error: could not compile `async-native-tls` (lib) due to 7 previous errors
warning: build failed, waiting for other jobs to finish...
error[E0308]: mismatched types
   --> /Users/mxm/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-imap-0.9.1/src/imap_stream.rs:290:64
    |
290 |                 ready!(Pin::new(&mut this.inner).poll_read(cx, buf))?;
    |                                                  ---------     ^^^ expected `&mut [u8]`, found `&mut ReadBuf<'_>`
    |                                                  |
    |                                                  arguments to this method are incorrect
    |
    = note: expected mutable reference `&mut [u8]`
               found mutable reference `&mut ReadBuf<'_>`
note: method defined here
   --> /Users/mxm/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-io-0.3.28/src/lib.rs:60:12
    |
60  |         fn poll_read(
    |            ^^^^^^^^^

Some errors have detailed explanations: E0252, E0308.
For more information about an error, try `rustc --explain E0252`.
error: could not compile `async-imap` (lib) due to 9 previous errors
➜  capture git:(refraction-capture-async-imap) ✗
```